In [ ]:
import numpy as np
arr = np.array([1, 2, 3,6, 4, 5])
reversed_arr = arr[::-1]
print(reversed_arr)



[5 4 6 3 2 1]


In [ ]:
import numpy as np

array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
flattened_array1 = array1.flatten()

print(flattened_array1)


[1 2 3 2 4 5 1 2 3]


In [ ]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

are_equal = np.array_equal(arr1, arr2)
print( are_equal)


True


In [ ]:
import numpy as np

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])

# Step 1: Count occurrences of each value
counts = np.bincount(x)

# Step 2: Find the most frequent value
most_frequent_value = np.argmax(counts)

# Step 3: Find all indices of this value
indices = np.where(x == most_frequent_value)[0]

print(f"The most frequent value is {most_frequent_value}")
print(f"Indices of the most frequent value: {indices}")


The most frequent value is 1
Indices of the most frequent value: [0 5 7 8 9]


In [ ]:
import numpy as np

y=np.array([1,1,1,2,3,4,2,4,3,3])

counts=np.bincount(y)
print(counts)

most_frequent_value=np.argmax(counts)

indices= np.where(y==most_frequent_value)[0]

print(f"The most frequent value is {most_frequent_value}")
print(f"Indices of the most frequent value: {indices}")



[0 3 2 3 2]
The most frequent value is 1
Indices of the most frequent value: [0 1 2]


In [ ]:
import numpy as np

gfg=np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

total_sum=np.sum(gfg)

print(total_sum)

row_sum=np.sum(gfg,axis=1)

print(row_sum)

col_sum=np.sum(gfg,axis=0)

print(col_sum)


45
[[14]
 [16]
 [15]]
[[20  9 16]]


In [ ]:
import numpy as py

n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])

# Sum of diagonal elements
sum_diagonal = np.trace(n_array)                    #computes the sum of the elements on the main diagonal of a 2D array (or matrix).
print(f"Sum of diagonal elements: {sum_diagonal}")

# Eigenvalues of the matrix
eigenvalues = np.linalg.eigvals(n_array)
print(f"Eigenvalues of the matrix: {eigenvalues}")

# Eigenvectors of the matrix
eigenvalues, eigenvectors = np.linalg.eig(n_array)
print(f"Eigenvectors of the matrix: \n{eigenvectors}")

# Inverse of the matrix
inverse_matrix = np.linalg.inv(n_array)
print(f"Inverse of the matrix: \n{inverse_matrix}")

# Determinant of the matrix
determinant = np.linalg.det(n_array)
print(f"Determinant of the matrix: {determinant}")





In [ ]:
import numpy as np

# Define matrices
p = np.array([[1, 2], [2, 3]])
q = np.array([[4, 5], [6, 7]])

# Matrix multiplication
product = np.dot(p, q)
print("Matrix Product:")
print(product)

# Flatten the matrices into vectors
p_flat = p.flatten()
q_flat = q.flatten()

# Stack the flattened matrices into a 2D array
stacked_matrices = np.vstack([p_flat, q_flat])

# Compute the covariance matrix
covariance_matrix = np.cov(stacked_matrices, bias=False)
print("Covariance Matrix:")
print(covariance_matrix)


Matrix Product:
[[16 19]
 [26 31]]
Covariance Matrix:
[[0.66666667 1.        ]
 [1.         1.66666667]]


In [ ]:
import numpy as np

x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

# inner product
inner_product = np.dot(x, y.T)        #  y.T denotes the transpose of y so that the dot product is correctly computed between corresponding dimensions.
print("Inner Product (Matrix Multiplication):")
print(inner_product)

#outer product
outer_product = np.outer(x.flatten(), y.flatten())
print("Outer Product:")
print(outer_product)





Inner Product (Matrix Multiplication):
[[17 52]
 [13 62]]
Outer Product:
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]


In [ ]:
import numpy as np

array = np.array([[1, -2, 3], [-4, 5, -6]])
abs_array = np.abs(array)

print(abs_array)


[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np

array = np.array([[1, -2, 3], [-4, 5, -6]])

# Flattened array
flattened_percentiles = np.percentile(array, [25, 50, 75])

column_percentiles = np.percentile(array, [25, 50, 75], axis=0)

row_percentiles = np.percentile(array, [25, 50, 75], axis=1)

print("Percentiles of flattened array (25th, 50th, 75th):")
print(flattened_percentiles)

print("\nPercentiles for each column (25th, 50th, 75th):")
print(column_percentiles)

print("\nPercentiles for each row (25th, 50th, 75th):")
print(row_percentiles)


Percentiles of flattened array (25th, 50th, 75th):
[-3.5 -0.5  2.5]

Percentiles for each column (25th, 50th, 75th):
[[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]

Percentiles for each row (25th, 50th, 75th):
[[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]


In [ ]:
import numpy as np

array = np.array([[1, -2, 3], [-4, 5, -6]])

# Flattened array
mean_flattened = np.mean(array)
median_flattened = np.median(array)
std_flattened = np.std(array)

# For each column
mean_columns = np.mean(array, axis=0)
median_columns = np.median(array, axis=0)
std_columns = np.std(array, axis=0)

# For each row
mean_rows = np.mean(array, axis=1)
median_rows = np.median(array, axis=1)
std_rows = np.std(array, axis=1)

print("Mean, Median, and Standard Deviation of flattened array:")
print(f"Mean: {mean_flattened}, Median: {median_flattened}, Std: {std_flattened}")

print("\nMean, Median, and Standard Deviation for each column:")
print(f"Mean: {mean_columns}")
print(f"Median: {median_columns}")
print(f"Std: {std_columns}")

print("\nMean, Median, and Standard Deviation for each row:")
print(f"Mean: {mean_rows}")
print(f"Median: {median_rows}")
print(f"Std: {std_rows}")


Mean, Median, and Standard Deviation of flattened array:
Mean: -0.5, Median: -0.5, Std: 3.8622100754188224

Mean, Median, and Standard Deviation for each column:
Mean: [-1.5  1.5 -1.5]
Median: [-1.5  1.5 -1.5]
Std: [2.5 3.5 4.5]

Mean, Median, and Standard Deviation for each row:
Mean: [ 0.66666667 -1.66666667]
Median: [ 1. -4.]
Std: [2.05480467 4.78423336]


In [ ]:
import numpy as np

array = np.array([10, 52, 62, 16, 16, 54, 453])

#  Sorted array
sorted_array = np.sort(array)

#  Indices of sorted array
indices_sorted_array = np.argsort(array)

#  4 smallest elements
four_smallest_elements = np.sort(array)[:4]

#  5 largest elements
five_largest_elements = np.sort(array)[-5:]

print("Original array:")
print(array)

print("\nSorted array:")
print(sorted_array)

print("\nIndices of sorted array:")
print(indices_sorted_array)

print("\n4 smallest elements:")
print(four_smallest_elements)

print("\n5 largest elements:")
print(five_largest_elements)


Original array:
[ 10  52  62  16  16  54 453]

Sorted array:
[ 10  16  16  52  54  62 453]

Indices of sorted array:
[0 3 4 1 5 2 6]

4 smallest elements:
[10 16 16 52]

5 largest elements:
[ 16  52  54  62 453]


In [ ]:
import numpy as np

array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

# i. Integer elements only
integer_elements = array[array == np.floor(array)]

# ii. Float elements only (including fractional part)
float_elements = array[array != np.floor(array)]

print("Original array:")
print(array)

print("\nInteger elements only:")
print(integer_elements)

print("\nFloat elements only:")
print(float_elements)


Original array:
[1.  1.2 2.2 2.  3.  2. ]

Integer elements only:
[1. 2. 3. 2.]

Float elements only:
[1.2 2.2]
